CREATE SEQUENCE TPARM_PRODT_COMPL_SEQ START WITH 1 INCREMENT BY 1;
create table TPARM_PRODT_COMPL(
	id int,
	CPARM_PRODT_PREVD varchar(100),
	CPARM_PRODT_COMPL varchar(100),
    CPARM_PRODT_12 varchar(10),
    CUSUAR_INCL varchar(50),
    HINCL_REG TIMESTAMP
);


CREATE SEQUENCE TFRMUL_BRANC_PREVD_SEQ START WITH 1 INCREMENT BY 1;
create table TFRMUL_BRANC_PREVD(
    CFRMUL_PPSTA_PREVD int,
    CFNALD_PPSTA int,
    RDOCTO_PRODT_PREVD varchar(100),
    ECMNHO_DOCTO_PREVD varchar(100),
    CUSUAR_SENHA_INCL varchar(50),
    HINCL_REG TIMESTAMP
);

create table TFRMUL_CPO_OBRIG(
	CFRMUL_PPSTA_PREVD int
);

create table TFRMUL_PRODT_BRANC(
    CFRMUL_PPSTA_PREVD int,
    CPRODT_NEGOC int
);
